export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERROR_LOADING_INGREDIENTS = 'ERROR_LOADING_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';


export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';

export const ORDER_BURGER_INIT = 'ORDER_BURGER_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_USER = 'AUTH_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE';

export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';