export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERROR_LOADING_INGREDIENTS = 'ERROR_LOADING_INGREDIENTS';



export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';

export const ORDER_BURGER_INIT='ORDER_BURGER_INIT';

export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED';
